---
title: "Final Grade Reflection"
author: "Janalyn Lao"
format: pdf
editor: visual
---

In the course of the first six weeks of STAT 331, I believe I have demonstrated understanding of a multitude of learning targets through the various assignments we've had throughout the course. The "Working With Data" learning targets I believe I've shown my understanding of are: WD-1 through the data_imports_practice activity; WD-2, WD-3, and WD-4 through preview activity 3, step 8; WD-5 through challenge 4 when combining my avocado and housing datasets; and WD-6 through lab 4 section 2, question 2. The "Reproducibility" learning targets I believe I've shown my understanding of are: R-1, and R-2 through all/any assignments provided; and the same applies for R-3 but a more specific example would be practice activity 3, step 8. The "Data Visualizations & Summarization" learning targets I believe I've shown my understanding of are: DVS-1, DVS-2, and DVS-3 through lab4 section 4; DVS-4 though lab 3 section 3, question 7; and DVS-5 through lab 4 section 3, question 3. The "Program Efficiency" learning targets I believe I've shown my understanding of are: PE-1 through lab 4; PE-2 through practice activity 3, step 8; and PE-4 through lab4.

I've demonstrated a commitment to continued learning through retrying and resubmitting challenges 3 and 4 and lab 3 until I'm able to receive an "S" on all aspects of the assignment. Because I want these assignments to reflect my full effort and commitment, I always aim to edit and resubmit my assignments that have a grade of "G". I've also found myself searching the internet for new ways to improve certain aspects of my plots and have found multiple ways to edit and personalize them to my liking. I've gotten suggestions to improve the formatting of my code to make it more human-readable and displaying my data as a way to provide evidence for my analysis and I believe I've been doing a good job of keeping them in mind on the following assignments.

As a team member, I believe I've grown through communication and being open to collaborate with my team members on assignments. When my group and I can't figure out problems together as a whole, I've offered to ask questions for them on Discord, though we are usually able to work it out together. When we are working in class, it can be hard to be in constant communication since we usually sit in pairs, however, as a facilitator, I will try to check in and include the other members if we are stuck on a problem or if it seems like the others are struggling. I've personally grown to not feel like a question I'm asking is too simple or "dumb" to ask since my group is usually very kind and willing to stop to help me understand better. When it comes to me explaining my reasoning, I always try to keep an open mind and be receptive to any disagreements anyone may have because I know that I, too, can make mistakes. As a leader, I believe I've grown in inclusivity and fostering a welcoming environment. I love hearing and including everyone in conversations and creating an environment that everyone feels comfortable in. I don't want anyone to feel like their thoughts and opinions don't matter and I know that some group members can be more vocal than others so as a leader, it is my job to read social cues and encourage everyone to participate.

I've contributed to creating a respectful classroom learning community by being mindful and respectful of everyone's place through their personal journeys, whether it be their personal or academic journey. To elaborate, everyone works and learns at different paces and in places where I think something is easy, doesn't mean it's easy or as simple for everyone else and vice versa. With this in mind, I aim to be mindful when asking questions or giving advice or help. Similarly, everyone is at different places of their own personal development and journey and can be going through something I have no idea about. I try to always approach everyone with an open mind and I aim to always respect one's sexuality, pronouns, gender expression, gender identity, and anything else that they entrust to me.

The two goals I set for myself at the beginning of the course are staying on track with all the assignments and fully understanding what my code is doing throughout my assignments. I still believe I am doing a good job at accomplishing my goals because I've been on-track with assignments and turning them all in before the due date and all assignments are approached with a purposeful mindset and I can understand what I was doing when looking back on them. With everything I've accomplished in class, I believe I have the letter grade of an A.
