---
title: "Practice Activity 9: Simulation"
author: Janalyn Lao
format:
  html: 
    self-contained: true
editor: visual
theme: cyborg
code-fold: show
---

## Question 1

```{r}
#| message: false

library(tidyverse)
```

```{r}
# What is the 95th percentile for trumpet weight?

qnorm(.95, mean = 2.5, sd = 1)

```

## Question 2

```{r}
# What is the 10th percentile for trombone weight?

qnorm(.10, mean = 4.6, sd = 0.8)
```

## Question 3

```{r}
# About what percent of trombones do you expect to be more than 5 pounds?

(1 - pnorm(5, mean = 4.6, sd = 0.8)) * 100
```

## Question 4

```{r}
# About what percent of reed instruments do you expect to be more than 5 pounds?

(1 - pnorm(5, mean = 4, sd = sqrt(8))) * 100

```

## Question 5

```{r}
# Simulate 100 random trombone weights. How many of them were below 4 pounds?

rand_trombone <- rnorm(100, mean = 4.6, sd = 0.8)
sum(rand_trombone < 4)

```

## Question 6

```{r}
music_man <- function(n_tromb, n_trump, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  trumpets <- runif(n_trump, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)
  
  return(sum(trombones, trumpets, reeds))
  
}

set.seed(1957)

my_weights <- rerun(.n = 1000, 
                    music_man(n_tromb = 76, 
                              n_trump = 110,
                              n_reed = 1035)
                    ) |> 
  flatten_dbl()

sum(my_weights < 4532)
```
