---
title: "My Growth as a Data Scientist"
author: Janalyn Lao
format: html
editor: visual
---

In taking STAT 331, I believe I've improved as a practitioner and student of data science through various assignments I've completed through the quarter. Before taking this class, I had no knowledge of working with data but I am now more confident in my skills as a data scientist. When working with data, I've learned a variety of skills such as: importing, selecting, and manipulating new data. In the **data_imorts_practice** preview activity, I learned how to import data from various formats like: .csv, .txt, and .xlsx files. Moreover, in almost every assignment submitted in the portfolio, I\'ve practiced importing data from .csv files in order to use the data needed for labs and practice activities. In **lab 7 question \_\_,** I demonstrated selecting specific data through filtering by columns in order to simplify my data to keep only what I needed for the specific problem. In **lab 4, question \_\_,** I demonstrated filtering data rows for numeric and character data. In **lab 3 question \_\_,** I modified participants\' ethnicities to better categorize them for easier use in the future. In **lab 4 question \_\_,** I demonstrated being able to use mutating joints and in **question \_\_,** I demonstrated being able to use filtering joins.

As a growing data scientist, I've also learned how to visualize and summarize data through the assignments I've completed in this class. In **lab 4 question \_\_**, I recreated a creative visualization of my data to display the proportion of mean avocados sold per region of California and I also modified this plot to make it more visually appealing for readers. I\'ve also created multiple data summaries, such as the one in **lab 4 question \_\_**.

With all these skills learned, I believe I have grown tremendously and will be able to grow on these skills in the future when it comes to more data processing and manipulating. The skills I\'ve learned in this class have set me up for success in the future.
